<Project>

    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <IsTestProject Condition="'$(IsTestProject)' == ''">true</IsTestProject>
        <IsUnitTestProject Condition="'$(IsUnitTestProject)' == ''">false</IsUnitTestProject>
        <OutputType Condition="'$(IsTestProject)' == 'true'">Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner Condition="'$(IsTestProject)' == 'true'">true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup Label="GlobalTestsItemGroup" Condition="'$(IsTestProject)' == 'true'">
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="AutoFixture.Xunit3" />
        <PackageReference Include="coverlet.MTP" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3.mtp-v2" />
        <Using Include="AutoFixture" />
        <Using Include="AutoFixture.Xunit3" />
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup Label="UnitTestsItemGroup" Condition="'$(IsUnitTestProject)' == 'true'">
        <PackageReference Include="AutoFixture.AutoNSubstitute" />
        <PackageReference Include="NSubstitute" />
        <Using Include="AutoFixture.AutoNSubstitute" />
        <Using Include="NSubstitute" />
    </ItemGroup>
</Project>
