changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🔥 Hot Fixes
      labels:
        - hotfix  
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: ✨ New Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
    - title: 🛠 Enhancements
      labels:
        - enhancement
    - title: 📦 Other Changes
      labels:
        - "*"