<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net8.0;net10.0</TargetFrameworks>
        <IsTestProject>false</IsTestProject>
        <IsUnitTestProject>false</IsUnitTestProject>
        <OutputType>Library</OutputType>
        <RootNamespace>Dapper.SimpleSqlBuilder.UnitTestHelpers</RootNamespace>
        <AssemblyName>Dapper.SimpleSqlBuilder.UnitTestHelpers</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="AutoFixture.AutoNSubstitute" />
        <PackageReference Include="AutoFixture.Xunit3" />
        <PackageReference Include="xunit.v3.extensibility.core" />
        <Using Include="AutoFixture" />
        <Using Include="AutoFixture.AutoNSubstitute" />
        <Using Include="AutoFixture.Xunit3" />
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
